### ISSUE TITLE
orWall borks whole device when many applications are given Internet access

### ISSUE THREAD

**Issue by cyl-us** [EthACKdotOrg/orWall#67]
I thought it was Orbot doing it at first, due to Orbot being more prone to failure in the past, but upon further experimentation, it seems to be orWall doing this.

I had my superuser application set to grant orWall root access automatically without prompting me. This has worked quite well until recently (probably at the last update, but I wasn't paying attention at the time), but now, if orWall is granted root access, I often lose my ability to install/uninstall applications, clear application data, and even open most of my applications. Many applications fail to autostart as well, including Orbot, SMSsync, and Weather Notification (all available on F-Droid). The (AOSP, I think) calendar home screen widget also often fails to load, and the device becomes very slow to respond.

 I find that whenever orWall is not granted root access, much less fails, and I am able to clear orWall's data or uninstall orWall, either of which fixes the rest of the problems.

If you know how I can provide you with more specific information, I'd be happy to tell more. OrWall is one of my must-have applications, so I'd love to see this resolved.

UPDATE: It seems that the issue only occurs when many applications are given Internet access. When only a few are checked in orWall, there isn't any problem. It seems the probability of seeing the issue goes up as you add more applications to the approved list. Are IP tables stored in RAM or something? It's also important to note that this issue usually is seen right after the device boots, though sometimes happens later.

**Comment by cjeanneret** [comment]
Hello,

Just in order to get a deeper check: what happens if you disable, wait a bit, then re-enable orWall (home screen, first switch)? Does it also "explode"?

Purpose of the question: enabling orWall calls the same method as boot time. If it doesn't bork your device network, this means there's "something else" somewhere between the boot process and the rules application.

Thanks in advance for your feedback! Oh and, happy new year ;).

**Comment by cyl-us** [comment]
Sorry for the delay, the email alerting me to your comment got burried in a sudden wave of spam.

Stopping orWall (version 1.0.4) and restarting it a bit latter does not cause the problem, as the problem is that the device is prevented from fully initiating. (I think. It seems that some core components such as the uninstalled, the component that calculates application storage space, and some other things are prevented from starting.) Once everything is running, orWall doesn't shut everything down or retroactively stop it from having started.

The new update you tweeted about today (version 1.0.5) likewise doesn't have the issue at all. I gave Internet access to every application orWall allows me to, including all the ones that I don't want actually accessing the Internet, which probably about tripples the ammount of checked applications. There was some slowness at first after rebooting, but the device booted normally and everything is working.

**Comment by cjeanneret** [comment]
\o/ wooohooo!
So the queuing seems to work as expected.

My explanation:
Boot process is really heavy, with many threads/processes. Android can multi-process, but there are some limits. The fact orwall looped through all the configured apps and, for each, runs a command "in the loop" probably ate too many "frames", locking out the others apps.
Now that there's a queue (well, not really a queue but something alike), the system might delay a bit the command application, in order to let other apps/boot process have access to the resources.

I guess I can close the issue now? :)

**Comment by patcon** [comment]
:heart:
