### ISSUE TITLE
Orbot seems to be blocked by Orwall

### ISSUE THREAD

**Issue by silwol** [EthACKdotOrg/orWall#71]
I have a Fairphone 1, with the manufacturer's version of ASOP installed (4.2.2) which has root enabled by default.
I would like to lock some applications into TOR-only connections (in my case owncloud and DAVDroid) and have them connect to a hidden service. I already had Orbot installed and running properly, then installed Orwall 1.0.5 from f-droid store. Enabled the firewall and selected the apps in the list. Everything worked as expected, the apps connected to the hidden service.
After a reboot, the following happened (no matter if on 3G or on WLAN):
Orwall seems to be started automatically, Orbot does not get started automatically (even though configured that way, but I don't think this has anything to do with this problem). When I start Orbot and tell it to connect, it stays in the "Orbot is starting…" mode.
![shot13](https://cloud.githubusercontent.com/assets/2116919/6218886/50b8a91a-b623-11e4-8135-32df578ba77e.png)

To me it seems as if Orbot is blocked from connecting to the net through Orwall.
Here you find screenshots of my configuration.
![shot0](https://cloud.githubusercontent.com/assets/2116919/6218872/305a443a-b623-11e4-8b08-e879ce8f7f69.png)
![shot1](https://cloud.githubusercontent.com/assets/2116919/6218875/38e92c92-b623-11e4-89bb-2e8a39ae2648.png)
![shot3](https://cloud.githubusercontent.com/assets/2116919/6218890/64f6e25c-b623-11e4-98d6-04f188e40e2b.png)
![shot4](https://cloud.githubusercontent.com/assets/2116919/6218892/68cda5e6-b623-11e4-9b92-a436dc1a25fa.png)
![shot6](https://cloud.githubusercontent.com/assets/2116919/6218897/7482a4cc-b623-11e4-8dfe-9e2dbdbaa4a6.png)
![shot7](https://cloud.githubusercontent.com/assets/2116919/6218898/78569d10-b623-11e4-8b88-dfb5ec5fe1f4.png)
![shot8](https://cloud.githubusercontent.com/assets/2116919/6218901/7d338d52-b623-11e4-990a-1ac91113afee.png)
![shot9](https://cloud.githubusercontent.com/assets/2116919/6218903/830f5f8a-b623-11e4-84cd-d10d8fbbc75e.png)
![shot10](https://cloud.githubusercontent.com/assets/2116919/6218905/87088d0a-b623-11e4-99ca-6358d5669ec2.png)
![shot11](https://cloud.githubusercontent.com/assets/2116919/6218908/8b38a46e-b623-11e4-9094-24a35def8fb4.png)
![shot12](https://cloud.githubusercontent.com/assets/2116919/6218911/905474dc-b623-11e4-9824-f4717eac49fa.png)

Please let me know if you require any further information.

**Comment by silwol** [comment]
Output from iptables -vnL with orwall enabled:

Chain INPUT (policy ACCEPT 3095 packets, 1022K bytes)
 pkts bytes target     prot opt in     out     source               destination         
 391K   61M bw_INPUT   all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 oem_fwd    all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 fw_FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 bw_FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 natctrl_FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 2854 packets, 344K bytes)
 pkts bytes target     prot opt in     out     source               destination         
 389K   42M bw_OUTPUT  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain bw_FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain bw_INPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
42093   55M            all  --  !lo+   *       0.0.0.0/0            0.0.0.0/0            ! quota globalAlert: 2097152 bytes 
 569K   67M RETURN     all  --  lo     *       0.0.0.0/0            0.0.0.0/0           
 486K  603M            all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner socket exists

Chain bw_OUTPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
22624 1275K            all  --  *      !lo+    0.0.0.0/0            0.0.0.0/0            ! quota globalAlert: 2097152 bytes 
 569K   67M RETURN     all  --  *      lo      0.0.0.0/0            0.0.0.0/0           
 311K   30M            all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner socket exists

Chain costly_shared (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 penalty_box  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain fw_FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain fw_INPUT (0 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain fw_OUTPUT (0 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain natctrl_FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain oem_fwd (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain oem_out (0 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain penalty_box (1 references)
 pkts bytes target     prot opt in     out     source               destination

**Comment by silwol** [comment]
Output from iptables -vnL -t nat with orwall enabled:
Chain PREROUTING (policy ACCEPT 13 packets, 4464 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 2738  857K oem_nat_pre  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain INPUT (policy ACCEPT 3 packets, 668 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0           !127.0.0.1            tcpflags: 0x17/0x02 owner UID match 10061 redir ports 9040
    0     0 REDIRECT   udp  --  *      *       0.0.0.0/0           !127.0.0.1            udp dpt:53 owner UID match 10061 redir ports 5400
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0           !127.0.0.1            tcpflags: 0x17/0x02 owner UID match 10059 redir ports 9040
    0     0 REDIRECT   udp  --  *      *       0.0.0.0/0           !127.0.0.1            udp dpt:53 owner UID match 10059 redir ports 5400

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
10330  644K natctrl_nat_POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain natctrl_nat_POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain oem_nat_pre (1 references)
 pkts bytes target     prot opt in     out     source               destination

**Comment by cjeanneret** [comment]
Hello,

That's weird:
* your ```iptables -vnL``` output doesn't show any of orwall rules
* the POLICY for output/input chains in filter table are set to "ACCEPT", orwall enforces them to DROP through both init-script *and* app startup (seems you don't have init-script support, 4.2.2 power -.-)
* only the "nat" table seems to get some orwall-related stuff, with the redirections — and it's incomplete: there should be some orbot-related rule at the top of the OUTPUT chain.

Soo… seems there's some weird stuff on this phone. Have you tried to disable and re-enable orwall?
You might as well want to check orbot logs in order to see what's happening.

In the present setup, the unchecked apps should be able to access the Net… as well as orbot, as there shouldn't be any redirection for this one.

Also, android 4.2.2 is crappy, and has some bad security flaw that won't be corrected… Might be worth to check if there's some upgrade possibility. But I doubt this has anything to do with orwall/orbot problems.

**Comment by silwol** [comment]
Thanks for your answer.

Might the whole problem be caused by the fact that I don't have any init-script support on my phone?
I did a short test: I removed Orwall, restarted the phone and then installed Orwall again. When I lock applications into tor, this seems to work now. The other applications can still access the net directly, and there are no DROP in the rules at all.

Once Orwall was installed and out of service as described in the beginning, disabling and re-enabling it did not change anything.

Orbot logs show only a few lines, with "Connecting to control port: <portnum>" twice in the last two lines, then they stop while Orbot is trying to connect.

You're right, Android 4.2.2 is crappy. I guess that's the fate of somebody who chose to support the right thing and bought a Fairphone :-( At least they finally released a [statement](https://www.fairphone.com/2014/12/09/our-approach-to-software-and-ongoing-support-for-the-first-fairphones/) about that, but it does not sound very satisfying.

Is there any easy way I could manually apply the init script, e.g. through ADB to test out if it works then?

**Comment by cjeanneret** [comment]
* even if init script isn't working properly, orwall re-add the POLICY in order to ensure nothing goes out
* your iptables outputs show one thing: orwall isn't started properly

I suspect orwall isn't started properly by the system at boot time: in a standard boot process, there are actually two stages for orwall:
* init-script (optional, but we're better when it's working as it's locking network until boot is complete)
* orwall app, started by the system once android is up n'running

You said: ```Orwall seems to be started automatically, Orbot does not get started automatically```
I guess that's the issue: android 4.2.2 shipped with the fairphone isn't supporting properly application running at startup time.
If orwall starts, you should get more things in the iptables output, for example rules dedicated for orbot, chain POLICY set to DROP for INPUT and OUTPUT… but you have nothing of that.

The few things in the nat table are probably due to the fact you checked some app before running the ```iptables -vnL -t nat``` command.

Currently, it might happen orwall is started after orbot, leading in some weird behavior but still, it's working (I didn't see anything regarding startup priorities nor dependencies yet).

I'm pretty sure you're hitting some weird thing, probably due to the fairphone rom customization. Would be nice if you could just poke in their forum in order to get some information regarding that issue.

It seems some people are porting [CM11 on the fairphone](https://forum.fairphone.com/t/cyanogenmod-11-for-fairphone-install-guide-experiences/1071), might be good to give a try?

Unfortunately, on my side, I cannot provide more help, especially if it's on android startup level: orwall requests the [correct right](https://github.com/EthACKdotOrg/orWall/blob/master/app/src/main/AndroidManifest.xml#L6) on this level and has a [receiver](https://github.com/EthACKdotOrg/orWall/blob/master/app/src/main/AndroidManifest.xml#L34-L43) in order to [initialize](https://github.com/EthACKdotOrg/orWall/blob/master/app/src/main/java/org/ethack/orwall/BootBroadcast.java) iptables…
More than that, I think I'm a bit stuck.

Seeing orbot isn't started properly at boot time seems to point a bug in the ROM, not orwall :(.

**Comment by silwol** [comment]
Thank you very much for your support so far. I don't think we can get any further with this as long as I am stuck with Android 4.2.2. I had great hopes in CM11 for the Fairphone, but it still seems to have some showstoppers, and appearently development has slowed down.
Right now I rely on a working OS on my phone, so I guess we can just close it for now. I will retry Orwall when I have either a different phone or a different OS on my Fairphone.

**Comment by c3ph3us** [comment]
did u try ?
http://forum.xda-developers.com/fairphone/orig-development/rom-cyanogenmod-11-4-4-4-kitkat-t2862874
