### ISSUE TITLE
"Iptables doesn't seem to be initialized"

### ISSUE THREAD

**Issue by takiainen** [EthACKdotOrg/orWall#84]
Orwall shows me the red banner all the time, despite of several reboots or clean install of rom. For some reason when I was running Exodus, the red banner disappeared after first boot after installation (as it should), but with every other ROM (Blisspop, AICP, SlimLP) the iptable warning remains.

Despite the warning, the firewall seems to work: apps are routed through tor, and apps that are not allowed do not get internet access.But obviously the red banner should not be there..

Currently I've got SlimSaber on my Oneplus with stock settings, no GAPPS.

**Comment by cjeanneret** [comment]
Hello,

There is an issue with the init-script on Lollipop, due to SELinux context switching during the boot time. I'm pretty sure this is your issue, and here are the consequences:
Upon boot time, iptables isn't correctly initialized. This can leads to data leaks, as the internet connection will be up *before* orWall has any chance to take the lead and close the firewall — this would allow some sneaky apps to send or receive stuff without your knowledge, even before you may interact with your android OS (i.e. before the display is correct), especially if you have Wireless connection ON upon boot.

You might find more information in #79 regarding the SELinux issue.

If you don't get the red banner on some roms, this might be due to:
- older android (4.x)
- no selinux context switching upon boot

I unfortunately have to close this issue, as we're already trying to get a fix for that — hopefully NOT depending on the "su" version — but this isn't easy :(.

Cheers,

C.
