### ISSUE TITLE
Add instructions for "root access"

### ISSUE THREAD

**Issue by bnvk** [EthACKdotOrg/orWall#89]
I just installed Orwall on a new install of CyanogenMod 12, and it is telling me root permission errors. It would really helpful to end users to offer more instructions (within the app) on how to grant proper access needed by Orwall!

**Comment by cjeanneret** [comment]
Hello,

well… err… CM provides root access, but you might need to activate it (in dev options) — never got this issue, on any rooted device.

I think it's useless to add more instructions, as it depends on:
- device in use
- android version
- android ROM
- root application (SuperSu, or any other su-enabling apk)

The only thing I can think of is "please refer to you ROM documentation in order to properly grant root access to orwall".

Cheers,

C.
